[build]
  command = "npm run build" # The command to build the SSR application
  publish = "dist/main.js"      # Path to the client-side output
  functions = "netlify/functions"  # Path to the server-side functions